# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 08:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='badgetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('Content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Other_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('Venue', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 7, 15, 16, 40, 52, 231000))),
                ('image', models.ImageField(upload_to=b'event')),
                ('register_url', models.CharField(max_length=100, null=True)),
                ('free', models.BooleanField(default=False)),
                ('url', models.CharField(default=b'/educational/', max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.levels')),
                ('tags', models.ManyToManyField(to='tikeshell.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'event')),
                ('alt_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=b'event')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 7, 15, 16, 40, 52, 234000))),
                ('venue', models.CharField(max_length=50)),
                ('tickets_no', models.IntegerField(default=0)),
                ('url', models.CharField(default=b'/entertainment/', max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.Category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.levels')),
                ('tags', models.ManyToManyField(to='tikeshell.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('pin', models.CharField(max_length=6)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('tickettype_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 7, 15, 16, 40, 52, 240000))),
                ('token', models.CharField(max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='tickettype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tike_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('Content', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.Show')),
            ],
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tikeshell.Account')),
                ('introduction', models.TextField()),
                ('hosted_shows', models.ManyToManyField(to='tikeshell.Show')),
            ],
            bases=('tikeshell.account',),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.Show'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.Account'),
        ),
        migrations.AddField(
            model_name='badgetype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.Other_events'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
