# Generated by Django 2.0.4 on 2018-05-15 06:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.BigIntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Other_events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('Venue', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 5, 15, 8, 51, 55, 401211))),
                ('register_url', models.CharField(max_length=100)),
                ('free', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='tikeshell.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event')),
                ('alt_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='event')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 5, 15, 8, 51, 55, 406719))),
                ('venue', models.CharField(max_length=50)),
                ('tickets_no', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.Category')),
                ('tags', models.ManyToManyField(to='tikeshell.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField()),
                ('pin', models.CharField(max_length=6)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('tickettype_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('payed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 5, 15, 8, 51, 55, 415730))),
            ],
        ),
        migrations.CreateModel(
            name='tickettype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tike_type', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tikeshell.Account')),
                ('introduction', models.TextField()),
            ],
            bases=('tikeshell.account',),
        ),
        migrations.AddField(
            model_name='show',
            name='tickettypes',
            field=models.ManyToManyField(to='tikeshell.tickettype'),
        ),
        migrations.AddField(
            model_name='mainpicture',
            name='mainpicture',
            field=models.ManyToManyField(to='tikeshell.Picture'),
        ),
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tikeshell.Show'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='hosted_shows',
            field=models.ManyToManyField(to='tikeshell.Show'),
        ),
    ]
