# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 08:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 16, 41, 12, 857000)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 16, 41, 12, 859000)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 16, 41, 12, 866000)),
        ),
    ]
