# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-17 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0002_auto_20180715_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 21, 3, 24, 401000)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 21, 3, 24, 406000)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 21, 3, 24, 416000)),
        ),
    ]
