# Generated by Django 2.0.4 on 2018-05-15 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0002_auto_20180515_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='other_events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 8, 58, 9, 574027)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 8, 58, 9, 577532)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 8, 58, 9, 588045)),
        ),
    ]
