# Generated by Django 2.0.4 on 2018-05-28 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0003_auto_20180515_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='Content',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='other_events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 13, 56, 923976)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 13, 56, 927982)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 13, 56, 937495)),
        ),
    ]
