# Generated by Django 2.0.4 on 2018-05-28 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0004_auto_20180528_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='tickettypes',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tikeshell.Show'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='other_events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 25, 8, 874822)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 25, 8, 879830)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 15, 25, 8, 890345)),
        ),
    ]
