# Generated by Django 2.0.4 on 2018-06-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0005_auto_20180528_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other_events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 9, 56, 47, 101040)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 9, 56, 47, 104044)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 9, 56, 47, 114562)),
        ),
    ]
