# Generated by Django 2.0.4 on 2018-06-06 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0006_auto_20180606_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='other_events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 10, 6, 47, 755472)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 10, 6, 47, 755472)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 10, 6, 47, 755472)),
        ),
        migrations.AddField(
            model_name='other_events',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tikeshell.levels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tikeshell.levels'),
            preserve_default=False,
        ),
    ]
