# Generated by Django 2.0.4 on 2018-06-26 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0009_auto_20180615_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='other_events',
            name='url',
            field=models.CharField(default='/educational/', max_length=100),
        ),
        migrations.AddField(
            model_name='show',
            name='url',
            field=models.CharField(default='/entertainment/', max_length=30),
        ),
        migrations.AlterField(
            model_name='other_events',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 11, 16, 21, 184337)),
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 11, 16, 21, 184337)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 11, 16, 21, 184337)),
        ),
    ]
