# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-27 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikeshell', '0011_auto_20180627_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='token',
            field=models.CharField(default='910285C5-15ED-4755-875E-59B820AC0454', max_length=72),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='other_events',
            name=b'date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 28, 5, 35, 17, 890000)),
        ),
        migrations.AlterField(
            model_name='show',
            name=b'date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 28, 5, 35, 17, 893000)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name=b'date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 28, 5, 35, 17, 899000)),
        ),
    ]
